### ISSUE TITLE
Release for ROS Noetic

### ISSUE THREAD

**Issue by jpbusch** [flynneva/udp_msgs#15]
Could you please release for ROS noetic, @flynneva?

- Referring to: https://github.com/flynneva/udp_msgs/pull/14
- I think that the version also needs to be updated

**Comment by flynneva** [comment]
@jpbusch sure I'll try and get this done this week. I'm traveling Mon-Fri so should have some time at the hotel 👍

**Comment by flynneva** [comment]
fyi @jpbusch sorry this took so long for me to get to...but here you go: https://github.com/ros/rosdistro/pull/39127

PR to release this package for noetic.

I'll go ahead and close this 👍🏼
