### ISSUE TITLE
Release for ROS 2 Jazzy

### ISSUE THREAD

**Issue by jpbusch** [flynneva/udp_msgs#16]
Hi @flynneva!
Are there any plans to release this package for ROS 2 Jazzy? I think there are only some small changes in the CI required.
Let me know if you can do this. Alternatively, I can also create a PR. :slightly_smiling_face:

**Comment by flynneva** [comment]
@jpbusch sure I can later today, happy to release it for more distros 👌

**Comment by jpbusch** [comment]
Great, thank you! This enables us to release our packages as well :+1:

**Comment by jpbusch** [comment]
@flynneva have you already had time to prepare the release?

**Comment by flynneva** [comment]
@jpbusch apologies for dropping this.

I just updated the CI here in this repo and made a new tag.

Making the release PRs now to rosdistro 👍

**Comment by flynneva** [comment]
@jpbusch PR here for rosdistro: https://github.com/ros/rosdistro/pull/41928
